# Generated by Django 4.2.30 on 2026-06-30 09:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_rename_fssai_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name_plural': 'food categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('food_type', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('VEGAN', 'Vegan')], db_index=True, default='VEG', max_length=20)),
                ('preparation_time', models.PositiveIntegerField(help_text='Preparation time in minutes.')),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out of Stock')], db_index=True, default='IN_STOCK', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='menu.foodcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'indexes': [models.Index(fields=['restaurant', 'category'], name='menu_menuit_restaur_6c96a2_idx'), models.Index(fields=['restaurant', 'is_available', 'stock_status'], name='menu_menuit_restaur_c0155a_idx'), models.Index(fields=['restaurant', 'is_featured'], name='menu_menuit_restaur_ac3d6e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('restaurant'), name='unique_menu_item_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(check=models.Q(('discount_price__isnull', True), ('discount_price__lt', models.F('price')), _connector='OR'), name='discount_price_less_than_price'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['restaurant', 'display_order'], name='menu_foodca_restaur_0ea78a_idx'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['restaurant', 'is_active'], name='menu_foodca_restaur_02542b_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('restaurant'), name='unique_food_category_name_per_restaurant'),
        ),
    ]
