# Generated by Django 4.2.30 on 2026-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
