# Generated by Django 4.2.30 on 2026-06-30 11:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
