# Generated by Django 4.2.30 on 2026-06-30 11:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_order_orderitem_order_orders_orde_custome_d33a93_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='ASSIGNED', max_length=24)),
                ('assigned_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to='accounts.deliverypartnerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))])),
                ('current_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='delivery.deliveryassignment')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['delivery_assignment', 'timestamp'], name='delivery_de_deliver_3ded26_idx'), models.Index(fields=['status', 'timestamp'], name='delivery_de_status_82f4ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('incentive', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='accounts.deliverypartnerprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_earnings', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'delivery earnings',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['delivery_partner', 'payment_status'], name='delivery_de_deliver_5e33d4_idx'), models.Index(fields=['created_at'], name='delivery_de_created_fc7df2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['delivery_partner', 'status'], name='delivery_de_deliver_892491_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['order', 'status'], name='delivery_de_order_i_257c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['assigned_at'], name='delivery_de_assigne_c17a32_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('DELIVERED', 'CANCELLED')), _negated=True), fields=('order',), name='unique_active_delivery_assignment_per_order'),
        ),
    ]
