# Generated by Django 4.2.30 on 2026-06-30 11:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_rename_fssai_license_number'),
        ('orders', '0002_order_orderitem_order_orders_orde_custome_d33a93_idx_and_more'),
        ('accounts', '0001_initial'),
        ('menu', '0003_menuitem_rating_menuitem_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to='accounts.customerprofile')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to='accounts.customerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.menuitemreview')),
                ('restaurant_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.restaurantreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant_review'), name='unique_restaurant_review_like'),
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.UniqueConstraint(fields=('user', 'menu_item_review'), name='unique_menu_item_review_like'),
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('restaurant_review__isnull', False), ('menu_item_review__isnull', True)), models.Q(('restaurant_review__isnull', True), ('menu_item_review__isnull', False)), _connector='OR'), name='review_like_targets_exactly_one_review'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['restaurant', 'is_visible'], name='reviews_res_restaur_b797b3_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['customer', 'created_at'], name='reviews_res_custome_bea0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['rating'], name='reviews_res_rating_e28bdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantreview',
            constraint=models.UniqueConstraint(fields=('restaurant', 'order'), name='unique_restaurant_review_per_order'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['menu_item', 'is_visible'], name='reviews_men_menu_it_2b71dd_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['customer', 'created_at'], name='reviews_men_custome_b2c5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['rating'], name='reviews_men_rating_730079_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitemreview',
            constraint=models.UniqueConstraint(fields=('menu_item', 'order'), name='unique_menu_item_review_per_order'),
        ),
    ]
