# Generated by Django 4.2.30 on 2026-06-30 10:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_orderitem_order_orders_orde_custome_d33a93_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_accounts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='accounts.customerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_repayments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('statement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='payments.creditaccount')),
            ],
            options={
                'ordering': ('-billing_month',),
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('REPAYMENT', 'Repayment'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.creditaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('COD', 'Cash on Delivery'), ('DILPDA_PAY_LATER', 'DilpDa Pay Later')], max_length=32)),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='accounts.customerprofile')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='payments.monthlystatement')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer', 'paid_at'], name='payments_re_custome_1b2b23_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('COD', 'Cash on Delivery'), ('DILPDA_PAY_LATER', 'DilpDa Pay Later')], max_length=32)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=80)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.customerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer', 'payment_status'], name='payments_pa_custome_4146dd_idx'), models.Index(fields=['order', 'payment_status'], name='payments_pa_order_i_01ef4c_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='monthlystatement',
            index=models.Index(fields=['credit_account', 'statement_status'], name='payments_mo_credit__76ffa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlystatement',
            constraint=models.UniqueConstraint(fields=('credit_account', 'billing_month'), name='unique_statement_per_account_month'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_account', 'transaction_type'], name='payments_cr_credit__6ca633_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['order'], name='payments_cr_order_i_76a20d_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['credit_status'], name='payments_cr_credit__a61319_idx'),
        ),
    ]
